feeds_advance_crawler.settings:
  type: config_object
  label: 'Advance Feeds Crawler Settings'
  mapping:
    nodejs_host:
      type: string
      label: 'Node.js server host for Scraper API'
    nodejs_port:
      type: string
      label: 'Node.js server port'
    proxy:
      type: string
      label: 'Proxy URL'
